apiVersion: v1
kind: Secret
metadata:
  name: clickee-coach-backend
  namespace: ${NAMESPACE_RAW}
type: Opaque
data:
  ENV: ${ENV}
  PRODUCTION: ${PRODUCTION}
  STAGE: ${STAGE}
  CLIENT_ID: ${CLIENT_ID}
  CLIENT_SECRET: ${CLIENT_SECRET}
  DOMAIN: ${DOMAIN}
  FORM_CLIENT_ID: ${FORM_CLIENT_ID}
  FORM_CLIENT_SECRET: ${FORM_CLIENT_SECRET}
  FORM_REDIRECT_URI: ${FORM_REDIRECT_URI}
  LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}
  MONGO_URI: ${MONGO_URI}
  NODE_ENV: ${NODE_ENV}
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  REDIRECT_URI: ${REDIRECT_URI}
  SERVICE_3000_NAME: ${SERVICE_3000_NAME}
  SERVICE_NAME: ${SERVICE_NAME}
  SERVICE_TAGS: ${SERVICE_TAGS}
  FRONTEND_URL: ${FRONTEND_URL}
 